apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-new
  namespace: default
spec:
  encryptedData:
    key: AgBeYHrxeUJZ5/N032vqay682sRZi5qVPu8dvwQuMw5KtKHj8rrPExaU0ubctI5OZX8kiRhiGcuKGIberwL8WbhBxU04IDi/h7MCxzjg4oIK5nQ+FH8rxDv7+KlBA+1Pw3twgCkCzIQo9mYvkEJN4QnSKMUc1Zn6bbu5o/JkUU1YS18chl11i5g9ioMi1W68YoNXVWanMgFZ3BVqy0U/llAMTr4qhSYMdpcBL2OeaJBG2hqtdgGTxg16eNarZEwxKe8QY4O0wHfxystLTbnMJ+9QjLswSGCZzZfKVwj+8DHnGWge4Rux2ugh1dfMbVsJeYcyxmAkCZXPCx+1rUH/6Wo+rskTaCpBMJnHcwSMRa/T38FiTjuQ1GH2j1UxbWgB5BHkgUV01YzTW2XMaCRc0ia3nFdFBT2gLBE0gcvVwetZoc7K6c6HvbJhndCGnQTGVolgSzbUKjOTTvOgG/7fGKCaRrQugNgXQEfeTlQCb8R4LXRqAfhzCKFXrG3sYtt9DmkoHmRjENHbL67U37/viNDC3ANFwXaJJFZyrUPOr34WxN0nKMdwgdgIWQzCB8iLAlwJCN3+0eyjuJEYJXYygyEWkmHeThDdcTA/GxCiI4NSMv2fX5P2VLTE1MXNtsufHCBsXMIIwxMwUEJNtwzaGYMXj2EqkYBii4LjWEN+jII8FjbVAZCEjaQMeePjwoR1o/AnQ+c0OhpKzYIoVlUbcw==
  template:
    metadata:
      creationTimestamp: null
      name: my-new
      namespace: default